spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/btc-training
    username: postgres
    password: ${POSTGRES_SUPERUSER_PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:scripts/data.sql
      schema-locations: classpath:scripts/schema.sql


