spring:
  profiles:
    active: pg
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 658838121329-im5h2fvhvqpkggpvkl5bfp5verso0ese.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret-key: 42f87806eb5e695882afe118505621537eb1ca450d6a074496028209502c3f51
    access-exp-delay: 90000000
    prefix: Bearer
    auth-header: Authorization